### ISSUE TITLE
download not downloading the image

### ISSUE THREAD

**Issue by hwchen2009** [rrwen/google_streetview#6]
--save_downloads=downloads only creates json file but not jpg images

**Comment by rrwen** [comment]
Hi @hwchen2009 

After some debugging and searching, I found out that Google has changed their pricing plan, which restricts free usage of their StreetView API:

https://developers.google.com/maps/documentation/streetview/usage-and-billing

Unfortunately, this means that you will need a billing plan to be able to download images (this was not the case when I developed this package).

You can however still request for metadata for free (which is why the preview still works).
